server:
  tangoname: exp/ec/pump1
  database: True # indicate whether Tango database is available
  serialport: COM3
  host: localhost #IP address or hostname; only required if no Tango database is set up
  port: 50005 # only required if no Tango database is set up 
  name: pump1 # only required when the server is started from python

#possible valve types:
#0: 3-way 120 degree Y valve
#1: 4-way 90 degree T valve
#2: 3-way 90 degree distribution valve
#3: 8-way 45 degree valve
#4: 4-way 90 degree valve
#6: 6-way 45 degree valve

# supported device types: PSD smooth flow, MVP

devices:
  1: #hardware address
    name: Reservoir cell inlet 1
    type: PSD
    class: PSD4_smooth
    valve type: 3-way 90 degree distribution valve
    valve alias:
      1: Reservoir
      2: Waste
      3: Cell
    syringevolume: 12500 #muL
    start rate: 20 #muL/s
    stop rate: 20 #muL/s
    return volume: 0 #muL
    acceleration: 10000 #steps/s^2
    backoff volume: 5 #muL
    default init rate: 200 #muL/s
    default rate: 50 #muL/s
    # you can override rates with their motor steps:
    #start velocity: 100
    #stop velocity: 100
    #return steps: 20
    #backoff steps: 100
    
  3: #hardware address
    name: Reservoir cell inlet 2
    type: PSD
    class: PSD4_smooth
    valve type: 3-way 90 degree distribution valve
    valve alias:
      1: Reservoir
      2: Waste
      3: Cell
    syringevolume: 12500 #muL
    start rate: 10 #muL/s
    stop rate: 10 #muL/s
    return volume: 0 #muL
    acceleration: 10000 #steps/s^2
    backoff volume: 10 #muL
    default init rate: 200 #muL/s
    default rate: 50 #muL/s
    
  2: #hardware address
    name: Cell outlet 1
    type: PSD
    class: PSD4_smooth
    valve type: 3-way 90 degree distribution valve
    valve alias:
      1: Cell
      2: not connected
      3: Waste
    syringevolume: 12500 #muL
    start rate: 10 #muL/s
    stop rate: 10 #muL/s
    return volume: 0 #muL
    acceleration: 10000 #steps/s^2
    backoff volume: 10 #muL
    default init rate: 200 #muL/s
    default rate: 50 #muL/s
    
  4: #hardware address
    name: Cell outlet 2
    type: PSD
    class: PSD4_smooth
    valve type: 3-way 90 degree distribution valve
    valve alias:
      1: Cell
      2: not connected
      3: Waste
    syringevolume: 12500 #muL
    start rate: 10 #muL/s
    stop rate: 10 #muL/s
    return volume: 0 #muL
    acceleration: 10000 #steps/s^2
    backoff volume: 10 #muL
    default init rate: 200 #muL/s
    default rate: 50 #muL/s
    
  5: #hardware address
    name: Distribution valve
    type: MVP
    class: Valve
    valve type: 4-way 90 degree valve
    valve alias:
      1: Reservoir cell inlet 1 #for example...
      2: Reservoir cell inlet 2
      3: Cell outlet 1
      4: Cell outlet 2

    
    
    